#include "Include/WinHeaders.hpp"
#include "PatternLoader.h"
#include "Helper/Misc/ZydisWrapper.h"
#include "Helper/Misc/DynImport.hpp"
#include <map>
#include <unordered_map>
#include "Core\Core.hpp"
#include "Core/DMA/DMAHandler.h"
#define FitchVars(var,vector) FitOffset((#var),&g_PatternData.##var,vector)

namespace IronMan::Core
{

	PatternData g_PatternData;



	namespace PatternLoader
	{
		ptr_t GetDataPattern(ptr_t address, int32_t dataOperandOffset, int32_t dataInstructionSize)
		{
			return GetDMA().Read<int32_t>(address + dataOperandOffset) + (address + dataInstructionSize);
		}

		void ClearOffset()
		{
			g_PatternData.CharacterState = 0;
			g_PatternData.ptr_GetMousePostion = 0;
			g_PatternData.ComponentLocationOffset = 0;
			g_PatternData.offset_UFunction_Func = 0;
			g_PatternData.offset_ProcessEvent = 0;
			g_PatternData.offset_ComponentSpaceTransforms = 0;
			g_PatternData.offset_ComponentToWorld = 0;
			g_PatternData.fnGetNames = 0;
			g_PatternData.UObjectArray = 0;
			g_PatternData.UObjectArrayNum = 0;
			g_PatternData.ElementsPerChunk = 0;
			g_PatternData.UWrold_Ptr = 0;
			g_PatternData.UWorld = 0;
			g_PatternData.offset_LocalPlayers = 0;
			g_PatternData.decryptLocalPlayers = 0;
			g_PatternData.offset_ViewportClient = 0;
			g_PatternData.decryptViewportClient = 0;
			g_PatternData.offset_PlayerController = 0;
			g_PatternData.decryptPlayerController = 0;
			g_PatternData.offset_UWorld = 0;
			g_PatternData.decryptPersistentLevel = 0;
			g_PatternData.offsetPersistentLevel = 0;
			g_PatternData.encryAActors = 0;
			g_PatternData.decryptAActors = 0;
			g_PatternData.offsetAActors = 0;
			g_PatternData.decryptUObject = 0;
			g_PatternData.decryptUObjectIndex = 0;
			g_PatternData.decryptUObjectArray = 0;
			g_PatternData.offset_UObjectFlags = 0;
			g_PatternData.offset_UObjectIndex = 0;
			g_PatternData.offset_UObjectNameNumber = 0;
			g_PatternData.offset_UObjectNameComparisonIndex = 0;
			g_PatternData.offset_UObjectOuter = 0;
			g_PatternData.offset_UObjectClass = 0;
			g_PatternData.UObjectSize = 0;
			g_PatternData.offset_UStruct_SuperStruct = 0;
			g_PatternData.offset_UStruct_Children = 0;
			g_PatternData.offset_UStruct_PropertiesSize = 0;
			g_PatternData.offset_UClassBaseChainArray = 0;
			g_PatternData.offset_UClassNumClassBasesInChainMinusOne = 0;
			g_PatternData.offset_UFunction_FunctionFlags = 0;

			g_PatternData.SteamResizeBuffer = 0;
			g_PatternData.UnrealEngineRender = 0;
			g_PatternData.EmptyMemory = 0;
			g_PatternData.fnFindTextInLocalizationTable = 0;
			g_PatternData.ExtFindTextInLocalizationTableRcx = 0;
			g_PatternData.ExtFindTextInLocalizationTableCall = 0;
			g_PatternData.fnGetComponentsByClass = 0;
			g_PatternData.offset_OwnedComponents = 0;
			g_PatternData.offset_OwnedActorComponent = 0;

			g_PatternData.fnLineTraceSingle = 0;
			g_PatternData.fnLineTraceSingleByChannel = 0;
			g_PatternData.pDefaultQueryParam = 0;
			g_PatternData.pDefaultResponseParam = 0;
			g_PatternData.fnFCollisionQueryParamsConstructible = 0;
			g_PatternData.fnFCollisionQueryParamsDestructor = 0;
			g_PatternData.fnGetTslSettingsInstance = 0;
			g_PatternData.offset_TslSettings = 0;
			g_PatternData.offset_ATslCharacterUnk1 = 0;
			g_PatternData.offset_ATslCharacterUnk2 = 0;
			g_PatternData.offset_WorldPhysicsScene = 0;
			g_PatternData.fnGetPhysXScene = 0;
			g_PatternData.fnSetHitResultFromShapeAndFaceIndex = 0;

			g_PatternData.offset_GetOffsets = 0;
			g_PatternData.offset_Is_Scope = 0;
			g_PatternData.offset_WorldLocation = 0;
			g_PatternData.offset_JudgeMap = 0;
			g_PatternData.offset_MapBaseAddr = 0;

			g_PatternData.offset_FireState = 0;
			g_PatternData.offset_bThirdPerson = 0;
			g_PatternData.offset_BackPackState = 0;
			g_PatternData.offset_Language = 0;
			g_PatternData.offset_ScopeCamera_Breath = 0;
			g_PatternData.offset_GameState = 0;
		}

		void FitOffset(std::string vars, ptr_t* pOut, std::vector<std::string> netvars)
		{
			for (int i = 0; i < netvars.size(); i++)
			{
				if (netvars[i].find(vars) != std::string::npos)
				{
					if (netvars[i].substr(vars.length()).at(0) == ':')
					{
						auto offset = netvars[i].substr(vars.length() + 1);
						*pOut = std::stoi(offset);
						break;
					}
				}
			}
		}

		void SetupOffset(std::vector<std::string> netvars)
		{
			/*FitchVars(CharacterState, netvars);
			FitchVars(ptr_GetMousePostion, netvars);
			FitchVars(offset_PhysScene, netvars);
			FitchVars(offset_PxScene, netvars);
			FitchVars(GameTimePtr, netvars);
			FitchVars(InputAxisProperties, netvars);
			FitchVars(retaddrofLineTrace, netvars);
			FitchVars(UObjectSort[0], netvars);
			FitchVars(UObjectSort[1], netvars);
			FitchVars(UObjectSort[2], netvars);
			FitchVars(UObjectSort[3], netvars);
			FitchVars(UObjectSort[4], netvars);
			FitchVars(offset_JmpR14, netvars);
			FitchVars(offset_JmpR15, netvars);
			FitchVars(offset_bIsCanted, netvars);
			FitchVars(offset_bSpawnBulletFromBarrel, netvars);
			FitchVars(ComponentLocationOffset, netvars);
			FitchVars(offset_UFunction_Func, netvars);
			FitchVars(offset_ProcessEvent, netvars);
			FitchVars(fnProcessEvent, netvars);
			FitchVars(offset_ComponentSpaceTransforms, netvars);
			FitchVars(offset_ComponentToWorld, netvars);
			FitchVars(fnGetNames, netvars);
			FitchVars(GNames, netvars);
			FitchVars(UObjectArray, netvars);
			FitchVars(UObjectArrayNum, netvars);
			FitchVars(ElementsPerChunk, netvars);
			FitchVars(UWrold_Ptr, netvars);
			FitchVars(UWorld, netvars);
			FitchVars(offset_OwningGameInstance, netvars);
			FitchVars(offset_LocalPlayers, netvars);
			FitchVars(offset_ViewportClient, netvars);
			FitchVars(offset_PlayerController, netvars);
			FitchVars(offsetAActors, netvars);
			FitchVars(offsetPersistentLevel, netvars);
			FitchVars(offset_UWorld, netvars);
			FitchVars(vtindex_GetWorld, netvars);
			FitchVars(decryptUWorld, netvars);
			FitchVars(decryptOwningGameInstance, netvars);
			FitchVars(decryptLocalPlayers, netvars);
			FitchVars(decryptViewportClient, netvars);
			FitchVars(decryptPlayerController, netvars);
			FitchVars(decryptPersistentLevel, netvars);
			FitchVars(encryAActors, netvars);
			FitchVars(decryptAActors, netvars);
			FitchVars(decryptUObject, netvars);
			FitchVars(decryptUObjectIndex, netvars);
			FitchVars(decryptUObjectArray, netvars);
			FitchVars(offset_UObjectFlags, netvars);
			FitchVars(offset_UObjectIndex, netvars);
			FitchVars(offset_UObjectNameNumber, netvars);
			FitchVars(offset_UObjectNameComparisonIndex, netvars);
			FitchVars(offset_UObjectOuter, netvars);
			FitchVars(offset_UObjectClass, netvars);
			FitchVars(UObjectSize, netvars);
			FitchVars(offset_UStruct_SuperStruct, netvars);
			FitchVars(offset_UStruct_Children, netvars);
			FitchVars(offset_UStruct_PropertiesSize, netvars);
			FitchVars(fnGetOffset, netvars);
			FitchVars(offset_UClassBaseChainArray, netvars);
			FitchVars(offset_UClassNumClassBasesInChainMinusOne, netvars);
			FitchVars(offset_UFunction_FunctionFlags, netvars);
			FitchVars(SteamResizeBuffer, netvars);
			FitchVars(GameDrawing, netvars);
			FitchVars(GameDrawing2, netvars);
			FitchVars(UnrealEngineRender, netvars);
			FitchVars(EmptyMemory, netvars);
			FitchVars(fnFindTextInLocalizationTable, netvars);
			FitchVars(ExtFindTextInLocalizationTableRcx, netvars);
			FitchVars(ExtFindTextInLocalizationTableCall, netvars);
			FitchVars(fnGetComponentsByClass, netvars);
			FitchVars(offset_OwnedComponents, netvars);
			FitchVars(offset_OwnedActorComponent, netvars);
			FitchVars(fnLineTraceSingle, netvars);
			FitchVars(fnLineTraceSingleByChannel, netvars);
			FitchVars(pDefaultQueryParam, netvars);
			FitchVars(pDefaultResponseParam, netvars);
			FitchVars(fnFCollisionQueryParamsConstructible, netvars);
			FitchVars(fnFCollisionQueryParamsDestructor, netvars);
			FitchVars(fnGetTslSettingsInstance, netvars);
			FitchVars(offset_TslSettings, netvars);
			FitchVars(offset_ATslCharacterUnk1, netvars);
			FitchVars(offset_ATslCharacterUnk2, netvars);
			FitchVars(offset_WorldPhysicsScene, netvars);
			FitchVars(fnGetPhysXScene, netvars);
			FitchVars(fnraycastIndex, netvars);
			FitchVars(fnSetHitResultFromShapeAndFaceIndex, netvars);
			FitchVars(offset_Is_Scope, netvars);
			FitchVars(offset_WorldLocation, netvars);
			FitchVars(offset_JudgeMap, netvars);
			FitchVars(offset_MapBaseAddr, netvars);
			FitchVars(offset_FireState, netvars);
			FitchVars(offset_bThirdPerson, netvars);
			FitchVars(offset_BackPackState, netvars);
			FitchVars(offset_Language, netvars);
			FitchVars(offset_ScopeCamera_Breath, netvars);
			FitchVars(offset_GameState, netvars);
			FitchVars(offset_UFont_LegacyFontSize, netvars);
			FitchVars(offset_UCanvas_SizeX, netvars);
			FitchVars(offset_UCanvas_SizeY, netvars);
			FitchVars(offset_UCurveVector_FloatCurves, netvars);
			FitchVars(offset_ULvel_WorldSettings, netvars);
			FitchVars(offset_SkeletalMeshSocket_SocketName, netvars);
			FitchVars(offset_SkeletalMeshSocket_BoneName, netvars);
			FitchVars(offset_SkeletalMeshSocket_RelativeLocation, netvars);
			FitchVars(offset_SkeletalMeshSocket_RelativeRotation, netvars);
			FitchVars(offset_SkeletalMeshSocket_RelativeScale, netvars);
			FitchVars(offset_SkeletalMeshSocket_bForceAlwaysAnimated, netvars);
			FitchVars(offset_USkeleton_Sockets, netvars);
			FitchVars(offset_USkeletalMesh_Skeleton, netvars);
			FitchVars(offset_USkeletalMesh_Sockets, netvars);
			FitchVars(offset_USkeletalMesh_RefSkeleton, netvars);
			FitchVars(offset_Actor_RootComponent, netvars);
			FitchVars(offset_Actor_Owner, netvars);
			FitchVars(offset_Actor_Instigator, netvars);
			FitchVars(offset_Actor_CustomTimeDilation, netvars);
			FitchVars(offset_Actor_LinearVelocity, netvars);
			FitchVars(offset_ATslGameState_NumAliveTeams, netvars);
			FitchVars(offset_ATslGameState_LerpSafetyZonePosition, netvars);
			FitchVars(offset_ATslGameState_LerpSafetyZoneRadius, netvars);
			FitchVars(offset_ATslGameState_LerpBlueZonePosition, netvars);
			FitchVars(offset_ATslGameState_LerpBlueZoneRadius, netvars);
			FitchVars(offset_ATslGameState_RedZonePosition, netvars);
			FitchVars(offset_ATslGameState_RedZoneRadius, netvars);
			FitchVars(offset_ATslGameState_BlackZonePosition, netvars);
			FitchVars(offset_ATslGameState_BlackZoneRadius, netvars);
			FitchVars(offset_ATslGameState_SafetyZonePosition, netvars);
			FitchVars(offset_ATslGameState_SafetyZoneRadius, netvars);

			FitchVars(offset_AController_Pawn, netvars);
			FitchVars(offset_AController_StateName, netvars);
			FitchVars(offset_AController_ControlRotation, netvars);
			FitchVars(offset_APawn_PlayerState, netvars);
			FitchVars(offset_APawn_Controller, netvars);
			FitchVars(offset_APawn_BaseEyeHeight, netvars);
			FitchVars(offset_APlayerCameraManager_PCOwner, netvars);
			FitchVars(offset_APlayerCameraManager_ViewTarget, netvars);
			FitchVars(offset_APlayerCameraManager_CameraCache, netvars);
			FitchVars(offset_MinimalViewInfo_FOV, netvars);
			FitchVars(offset_MinimalViewInfo_Location, netvars);
			FitchVars(offset_MinimalViewInfo_Rotation, netvars);
			FitchVars(offset_TViewTarget_POV, netvars);
			FitchVars(offset_CameraCacheEntry_Timestamp, netvars);
			FitchVars(offset_CameraCacheEntry_POV, netvars);
			FitchVars(offset_AHUD_BlockInputWidgetList, netvars);
			FitchVars(offset_AHUD_WidgetStateMap, netvars);
			FitchVars(offset_AHUD_DebugCanvas, netvars);
			FitchVars(offset_AHUD_Canvas, netvars);
			FitchVars(offset_UActorComponent_bRegistered, netvars);
			FitchVars(offset_UTslVehicleCommonComponent_FuelMax, netvars);
			FitchVars(offset_UTslVehicleCommonComponent_Fuel, netvars);
			FitchVars(offset_UTslVehicleCommonComponent_HealthMax, netvars);
			FitchVars(offset_UTslVehicleCommonComponent_Health, netvars);
			FitchVars(offset_USceneComponent_ComponentVelocity, netvars);
			FitchVars(offset_USceneComponent_RelativeLocation, netvars);
			FitchVars(offset_USceneComponent_RelativeRotation, netvars);
			FitchVars(offset_USceneComponent_AttachParent, netvars);
			FitchVars(offset_UPrimitiveComponent_LastRenderTimeOnScreen, netvars);
			FitchVars(offset_UPrimitiveComponent_LastRenderTime, netvars);
			FitchVars(offset_UPrimitiveComponent_LastSubmitTime, netvars);
			FitchVars(offset_UPrimitiveComponent_bRenderCustomDepth, netvars);
			FitchVars(offset_UPrimitiveComponent_BodyInstance, netvars);
			FitchVars(offset_USkinnedMeshComponent_SkeletalMesh, netvars);
			FitchVars(offset_USkinnedMeshComponent_MasterPoseComponent, netvars);
			FitchVars(offset_USkinnedMeshComponent_MasterBoneMap, netvars);
			FitchVars(offset_USkinnedMeshComponent_CurrentEditableComponentTransforms, netvars);
			FitchVars(offset_USkinnedMeshComponent_CurrentReadComponentTransforms, netvars);
			FitchVars(offset_UTslAnimInstance_ControlRotation_CP, netvars);
			FitchVars(offset_UTslAnimInstance_RecoilADSRotation_CP, netvars);
			FitchVars(offset_UTslAnimInstance_ScopingAlpha_CP, netvars);
			FitchVars(offset_UTslAnimInstance_LeanRightAlpha_CP, netvars);
			FitchVars(offset_UTslAnimInstance_LeanLeftAlpha_CP, netvars);
			FitchVars(offset_UTslAnimInstance_bIsScoping_CP, netvars);
			FitchVars(offset_UTslAnimInstance_bIsTPPAiming, netvars);
			FitchVars(offset_UTslAnimInstance_bIsAiming_CP, netvars);
			FitchVars(offset_UTslAnimInstance_bIsReloading_CP, netvars);
			FitchVars(offset_USkeletalMeshComponent_AnimScriptInstance, netvars);
			FitchVars(offset_UStaticMeshSocket_SocketName, netvars);
			FitchVars(offset_UStaticMeshSocket_RelativeLocation, netvars);
			FitchVars(offset_UStaticMeshSocket_RelativeRotation, netvars);
			FitchVars(offset_UStaticMeshSocket_RelativeScale, netvars);
			FitchVars(offset_UStaticMesh_Sockets, netvars);
			FitchVars(offset_UStaticMeshComponent_StaticMesh, netvars);
			FitchVars(offset_UWeaponMeshComponent_AttachedStaticComponentMap, netvars);
			FitchVars(offset_UWeaponMeshComponent_ReplicatedSkinParam, netvars);
			FitchVars(offset_UCharacterMovementComponent_Velocity, netvars);
			FitchVars(offset_UCharacterMovementComponent_JumpZVelocity, netvars);
			FitchVars(offset_UCharacterMovementComponent_WalkableFloorZ, netvars);
			FitchVars(offset_UCharacterMovementComponent_LastUpdateLocation, netvars);
			FitchVars(offset_UCharacterMovementComponent_LastUpdateRotation, netvars);
			FitchVars(offset_UCharacterMovementComponent_LastUpdateVelocity, netvars);
			FitchVars(offset_UCharacterMovementComponent_CurrentFloor, netvars);
			FitchVars(offset_UCharacterMovementComponent_bit4, netvars);
			FitchVars(offset_ACharacter_CharacterMovement, netvars);
			FitchVars(offset_ACharacter_Mesh, netvars);
			FitchVars(offset_UVehicleRiderComponent_SeatIndex, netvars);
			FitchVars(offset_UVehicleRiderComponent_LastVehiclePawn, netvars);
			FitchVars(offset_UWeaponProcessorComponent_EquippedWeapons, netvars);
			FitchVars(offset_UWeaponProcessorComponent_WeaponIndex, netvars);
			FitchVars(offset_ATslCharacterBase_Health, netvars);
			FitchVars(offset_HealthFlag1, netvars);
			FitchVars(offset_HealthFlag2, netvars);
			FitchVars(offset_HealthFlag3, netvars);
			FitchVars(offset_HealthIndex1, netvars);
			FitchVars(offset_HealthIndex2, netvars);
			FitchVars(offset_HealthXorKeys, netvars);
			FitchVars(offset_HealthDecryptFunction, netvars);
			FitchVars(offset_ATslCharacterBase_HealthMax, netvars);
			FitchVars(offset_ATslCharacterBase_WeaponProcessor, netvars);
			FitchVars(offset_ATslCharacter_Team, netvars);
			FitchVars(offset_ATslCharacter_InventoryFacade, netvars);
			FitchVars(offset_ATslCharacter_VehicleRiderComponent, netvars);
			FitchVars(offset_ATslCharacter_GroggyHealth, netvars);
			FitchVars(offset_ATslCharacter_GroggyHealthMax, netvars);
			FitchVars(offset_ATslCharacter_AimOffsets, netvars);
			FitchVars(offset_ATslCharacter_LastAimOffsets, netvars);
			FitchVars(offset_ATslCharacter_ScopingCamera, netvars);
			FitchVars(offset_ATslCharacter_SpectatedCount, netvars);
			FitchVars(offset_ATslCharacter_LastTeamNum, netvars);
			FitchVars(offset_ATslCharacter_CharacterName, netvars);
			FitchVars(offset_APlayerController_AcknowledgedPawn, netvars);
			FitchVars(offset_APlayerController_PlayerCameraManager, netvars);
			FitchVars(offset_APlayerController_MyHUD, netvars);
			FitchVars(offset_APlayerController_MapSig, netvars);
			FitchVars(offset_APlayerController_RotationInput, netvars);
			FitchVars(offset_APlayerController_InputYawScale, netvars);
			FitchVars(offset_APlayerController_InputPitchScale, netvars);
			FitchVars(offset_APlayerController_InputRollScale, netvars);
			FitchVars(offset_ATslPlayerController_MaxValidPing, netvars);
			FitchVars(offset_ATslPlayerController_PlayerInput, netvars);
			FitchVars(offset_APlayerState_PlayerName, netvars);
			FitchVars(offset_APlayerState_Ping, netvars);
			FitchVars(offset_ATslPlayerState_PlayerStatistics, netvars);
			FitchVars(offset_ATslPlayerState_PubgIdData, netvars);
			FitchVars(offset_ATslPlayerState_DamageDealtOnEnemy, netvars);
			FitchVars(offset_ATslPlayerState_PartnerLevel, netvars);
			FitchVars(offset_AWheeledVehicle_Mesh, netvars);
			FitchVars(offset_AWheeledVehicle_VehicleMovement, netvars);
			FitchVars(offset_ATslFloatingVehicle_Mesh, netvars);
			FitchVars(offset_ATslFloatingVehicle_VehicleCommonComponent, netvars);
			FitchVars(offset_ATslWheeledVehicle_VehicleCommonComponent, netvars);
			FitchVars(offset_ADroppedItem_Item, netvars);
			FitchVars(offset_UItem_StackCount, netvars);
			FitchVars(offset_UItem_ItemTableRowPtr, netvars);
			FitchVars(offset_ItemTableRowBase_ItemName, netvars);
			FitchVars(offset_ItemTableRowBase_ItemCategory, netvars);
			FitchVars(offset_ItemTableRowBase_ItemDetailedName, netvars);
			FitchVars(offset_ItemTableRowBase_ItemDescription, netvars);
			FitchVars(offset_ItemTableRowBase_ItemID, netvars);
			FitchVars(offset_UDroppedItemInteractionComponent_Item, netvars);
			FitchVars(offset_AInventory_Items, netvars);
			FitchVars(offset_UEquipableItem_EquipSlotID, netvars);
			FitchVars(offset_UEquipableItem_DurabilityMax, netvars);
			FitchVars(offset_UEquipableItem_Durability, netvars);
			FitchVars(offset_UEquipableItem_ReplicatedSkinItem, netvars);
			FitchVars(offset_AEquipment_Items, netvars);
			FitchVars(offset_AItemPackage_Items, netvars);
			FitchVars(offset_ATslWeapon_Mesh3P, netvars);
			FitchVars(offset_ATslWeapon_MuzzleAttachPoint, netvars);
			FitchVars(offset_ATslWeapon_FiringAttachPoint, netvars);
			FitchVars(offset_ATslWeapon_AttachedItem, netvars);
			FitchVars(offset_ATslWeapon_Gun_ScopingAttachPoint, netvars);
			FitchVars(offset_ATslWeapon_Gun_ScopingFocusPoint, netvars);
			FitchVars(offset_ATslWeapon_Gun_CurrentAmmoData, netvars);
			FitchVars(offset_ATslWeapon_Gun_CurrentZeroLevel, netvars);
			FitchVars(offset_ATslWeapon_Trajectory_TrajectoryGravityZ, netvars);
			FitchVars(offset_ATslWeapon_Trajectory_WeaponTrajectoryData, netvars);
			FitchVars(offset_WeaponTrajectoryData_TrajectoryConfig, netvars);
			FitchVars(offset_ATslProjectile_ProjectileConfig, netvars);
			FitchVars(offset_ATslProjectile_CollisionComp, netvars);
			FitchVars(offset_ATslProjectile_ExplosionDelay, netvars);
			FitchVars(offset_ATslProjectile_TimeTillExplosion, netvars);
			FitchVars(offset_UTslSettings_BallisticDragScale, netvars);
			FitchVars(offset_UTslSettings_BallisticDropScale, netvars);
			FitchVars(offset_UBodySetup_WalkableSlopeOverride, netvars);
			FitchVars(offset_UWidget_Visibility, netvars);
			FitchVars(offset_UWidget_Slot, netvars);
			FitchVars(offset_UCanvasPanelSlot_LayoutData, netvars);
			FitchVars(offset_UTslNewWorldMapWidget_MapGrid, netvars);
			FitchVars(offset_TslTrainingWorldMapWidget_TrainingMapGrid, netvars);
			FitchVars(offset_UMinimapCanvasWidget_SelectMinimapSizeIndex, netvars);
			FitchVars(offset_UMinimapCanvasWidget_MinimapSizeOffset, netvars);
			FitchVars(offset_UTslGameUserSettings_SelectMiniMapIndex, netvars);
			FitchVars(offset_AInventoryFacade_Inventory, netvars);
			FitchVars(offset_AInventoryFacade_Equipment, netvars);*/


			FitchVars(CharacterState, netvars);
			FitchVars(ptr_GetMousePostion, netvars);
			FitchVars(offset_PhysScene, netvars);
			FitchVars(offset_PxScene, netvars);
			FitchVars(GameTimePtr, netvars);
			FitchVars(InputAxisProperties, netvars);
			FitchVars(retaddrofLineTrace, netvars);
			FitchVars(UObjectSort[0], netvars);
			FitchVars(UObjectSort[1], netvars);
			FitchVars(UObjectSort[2], netvars);
			FitchVars(UObjectSort[3], netvars);
			FitchVars(UObjectSort[4], netvars);
			FitchVars(offset_JmpR14, netvars);
			FitchVars(offset_JmpR15, netvars);
			FitchVars(offset_bIsCanted, netvars);
			FitchVars(offset_bSpawnBulletFromBarrel, netvars);
			FitchVars(ComponentLocationOffset, netvars);
			FitchVars(offset_UFunction_Func, netvars);
			FitchVars(offset_ProcessEvent, netvars);
			FitchVars(fnProcessEvent, netvars);
			FitchVars(offset_ComponentSpaceTransforms, netvars);
			FitchVars(offset_ComponentToWorld, netvars);
			FitchVars(fnGetNames, netvars);
			FitchVars(GNames, netvars);
			FitchVars(UObjectArray, netvars);
			FitchVars(UObjectArrayNum, netvars);
			FitchVars(ElementsPerChunk, netvars);
			FitchVars(UWrold_Ptr, netvars);
			FitchVars(UWorld, netvars);
			FitchVars(offset_OwningGameInstance, netvars);
			FitchVars(offset_LocalPlayers, netvars);
			FitchVars(offset_ViewportClient, netvars);
			FitchVars(offset_PlayerController, netvars);
			FitchVars(offsetAActors, netvars);
			FitchVars(offsetPersistentLevel, netvars);
			FitchVars(offset_UWorld, netvars);
			FitchVars(vtindex_GetWorld, netvars);
			FitchVars(decryptUWorld, netvars);
			FitchVars(decryptOwningGameInstance, netvars);
			FitchVars(decryptLocalPlayers, netvars);
			FitchVars(decryptViewportClient, netvars);
			FitchVars(decryptPlayerController, netvars);
			FitchVars(decryptPersistentLevel, netvars);
			FitchVars(encryAActors, netvars);
			FitchVars(decryptAActors, netvars);
			FitchVars(decryptUObject, netvars);
			FitchVars(decryptUObjectIndex, netvars);
			FitchVars(decryptUObjectArray, netvars);
			FitchVars(offset_UObjectFlags, netvars);
			FitchVars(offset_UObjectIndex, netvars);
			FitchVars(offset_UObjectNameNumber, netvars);
			FitchVars(offset_UObjectNameComparisonIndex, netvars);
			FitchVars(offset_UObjectOuter, netvars);
			FitchVars(offset_UObjectClass, netvars);
			FitchVars(UObjectSize, netvars);
			FitchVars(offset_UStruct_SuperStruct, netvars);
			FitchVars(offset_UStruct_Children, netvars);
			FitchVars(offset_UStruct_PropertiesSize, netvars);
			FitchVars(fnGetOffset, netvars);
			FitchVars(offset_UClassBaseChainArray, netvars);
			FitchVars(offset_UClassNumClassBasesInChainMinusOne, netvars);
			FitchVars(offset_UFunction_FunctionFlags, netvars);
			FitchVars(SteamResizeBuffer, netvars);
			FitchVars(GameDrawing, netvars);
			FitchVars(GameDrawing2, netvars);
			FitchVars(UnrealEngineRender, netvars);
			FitchVars(EmptyMemory, netvars);
			FitchVars(fnFindTextInLocalizationTable, netvars);
			FitchVars(ExtFindTextInLocalizationTableRcx, netvars);
			FitchVars(ExtFindTextInLocalizationTableCall, netvars);
			FitchVars(fnGetComponentsByClass, netvars);
			FitchVars(offset_OwnedComponents, netvars);
			FitchVars(offset_OwnedActorComponent, netvars);
			FitchVars(fnLineTraceSingle, netvars);
			FitchVars(fnLineTraceSingleByChannel, netvars);
			FitchVars(pDefaultQueryParam, netvars);
			FitchVars(pDefaultResponseParam, netvars);
			FitchVars(fnFCollisionQueryParamsConstructible, netvars);
			FitchVars(fnFCollisionQueryParamsDestructor, netvars);
			FitchVars(fnGetTslSettingsInstance, netvars);
			FitchVars(offset_TslSettings, netvars);
			FitchVars(offset_ATslCharacterUnk1, netvars);
			FitchVars(offset_ATslCharacterUnk2, netvars);
			FitchVars(offset_WorldPhysicsScene, netvars);
			FitchVars(fnGetPhysXScene, netvars);
			FitchVars(fnraycastIndex, netvars);
			FitchVars(fnSetHitResultFromShapeAndFaceIndex, netvars);
			FitchVars(offset_Is_Scope, netvars);
			FitchVars(offset_WorldLocation, netvars);
			FitchVars(offset_JudgeMap, netvars);
			FitchVars(offset_MapBaseAddr, netvars);
			FitchVars(offset_FireState, netvars);
			FitchVars(offset_bThirdPerson, netvars);
			FitchVars(offset_BackPackState, netvars);
			FitchVars(offset_Language, netvars);
			FitchVars(offset_ScopeCamera_Breath, netvars);
			FitchVars(offset_GameState, netvars);
			FitchVars(offset_UFont_LegacyFontSize, netvars);
			FitchVars(offset_UCanvas_SizeX, netvars);
			FitchVars(offset_UCanvas_SizeY, netvars);
			FitchVars(offset_UCurveVector_FloatCurves, netvars);
			FitchVars(offset_ULvel_WorldSettings, netvars);
			FitchVars(offset_SkeletalMeshSocket_SocketName, netvars);
			FitchVars(offset_SkeletalMeshSocket_BoneName, netvars);
			FitchVars(offset_SkeletalMeshSocket_RelativeLocation, netvars);
			FitchVars(offset_SkeletalMeshSocket_RelativeRotation, netvars);
			FitchVars(offset_SkeletalMeshSocket_RelativeScale, netvars);
			FitchVars(offset_SkeletalMeshSocket_bForceAlwaysAnimated, netvars);
			FitchVars(offset_USkeleton_Sockets, netvars);
			FitchVars(offset_USkeletalMesh_Skeleton, netvars);
			FitchVars(offset_USkeletalMesh_Sockets, netvars);
			FitchVars(offset_USkeletalMesh_RefSkeleton, netvars);
			FitchVars(offset_Actor_RootComponent, netvars);
			FitchVars(offset_Actor_Owner, netvars);
			FitchVars(offset_Actor_Instigator, netvars);
			FitchVars(offset_Actor_CustomTimeDilation, netvars);
			FitchVars(offset_Actor_LinearVelocity, netvars);
			FitchVars(offset_ATslGameState_NumAliveTeams, netvars);
			FitchVars(offset_ATslGameState_LerpSafetyZonePosition, netvars);
			FitchVars(offset_ATslGameState_LerpSafetyZoneRadius, netvars);
			FitchVars(offset_ATslGameState_LerpBlueZonePosition, netvars);
			FitchVars(offset_ATslGameState_LerpBlueZoneRadius, netvars);
			FitchVars(offset_ATslGameState_RedZonePosition, netvars);
			FitchVars(offset_ATslGameState_RedZoneRadius, netvars);
			FitchVars(offset_ATslGameState_BlackZonePosition, netvars);
			FitchVars(offset_ATslGameState_BlackZoneRadius, netvars);
			FitchVars(offset_ATslGameState_SafetyZonePosition, netvars);
			FitchVars(offset_ATslGameState_SafetyZoneRadius, netvars);

			FitchVars(offset_AController_Pawn, netvars);
			FitchVars(offset_AController_StateName, netvars);
			FitchVars(offset_AController_ControlRotation, netvars);
			FitchVars(offset_APawn_PlayerState, netvars);
			FitchVars(offset_APawn_Controller, netvars);
			FitchVars(offset_APawn_BaseEyeHeight, netvars);
			FitchVars(offset_APlayerCameraManager_PCOwner, netvars);
			FitchVars(offset_APlayerCameraManager_ViewTarget, netvars);
			FitchVars(offset_APlayerCameraManager_CameraCache, netvars);
			FitchVars(offset_MinimalViewInfo_FOV, netvars);
			FitchVars(offset_MinimalViewInfo_Location, netvars);
			FitchVars(offset_MinimalViewInfo_Rotation, netvars);
			FitchVars(offset_TViewTarget_POV, netvars);
			FitchVars(offset_CameraCacheEntry_Timestamp, netvars);
			FitchVars(offset_CameraCacheEntry_POV, netvars);
			FitchVars(offset_AHUD_BlockInputWidgetList, netvars);
			FitchVars(offset_AHUD_WidgetStateMap, netvars);
			FitchVars(offset_AHUD_DebugCanvas, netvars);
			FitchVars(offset_AHUD_Canvas, netvars);
			FitchVars(offset_UActorComponent_bRegistered, netvars);
			FitchVars(offset_UTslVehicleCommonComponent_FuelMax, netvars);
			FitchVars(offset_UTslVehicleCommonComponent_Fuel, netvars);
			FitchVars(offset_UTslVehicleCommonComponent_HealthMax, netvars);
			FitchVars(offset_UTslVehicleCommonComponent_Health, netvars);
			FitchVars(offset_USceneComponent_ComponentVelocity, netvars);
			FitchVars(offset_USceneComponent_RelativeLocation, netvars);
			FitchVars(offset_USceneComponent_RelativeRotation, netvars);
			FitchVars(offset_USceneComponent_AttachParent, netvars);
			FitchVars(offset_UPrimitiveComponent_LastRenderTimeOnScreen, netvars);
			FitchVars(offset_UPrimitiveComponent_LastRenderTime, netvars);
			FitchVars(offset_UPrimitiveComponent_LastSubmitTime, netvars);
			FitchVars(offset_UPrimitiveComponent_bRenderCustomDepth, netvars);
			FitchVars(offset_UPrimitiveComponent_BodyInstance, netvars);
			FitchVars(offset_USkinnedMeshComponent_SkeletalMesh, netvars);
			FitchVars(offset_USkinnedMeshComponent_MasterPoseComponent, netvars);
			FitchVars(offset_USkinnedMeshComponent_MasterBoneMap, netvars);
			FitchVars(offset_USkinnedMeshComponent_CurrentEditableComponentTransforms, netvars);
			FitchVars(offset_USkinnedMeshComponent_CurrentReadComponentTransforms, netvars);
			FitchVars(offset_UTslAnimInstance_ControlRotation_CP, netvars);
			FitchVars(offset_UTslAnimInstance_RecoilADSRotation_CP, netvars);
			FitchVars(offset_UTslAnimInstance_ScopingAlpha_CP, netvars);
			FitchVars(offset_UTslAnimInstance_LeanRightAlpha_CP, netvars);
			FitchVars(offset_UTslAnimInstance_LeanLeftAlpha_CP, netvars);
			FitchVars(offset_UTslAnimInstance_bIsScoping_CP, netvars);
			FitchVars(offset_UTslAnimInstance_bIsTPPAiming, netvars);
			FitchVars(offset_UTslAnimInstance_bIsAiming_CP, netvars);
			FitchVars(offset_UTslAnimInstance_bIsReloading_CP, netvars);
			FitchVars(offset_USkeletalMeshComponent_AnimScriptInstance, netvars);
			FitchVars(offset_UStaticMeshSocket_SocketName, netvars);
			FitchVars(offset_UStaticMeshSocket_RelativeLocation, netvars);
			FitchVars(offset_UStaticMeshSocket_RelativeRotation, netvars);
			FitchVars(offset_UStaticMeshSocket_RelativeScale, netvars);
			FitchVars(offset_UStaticMesh_Sockets, netvars);
			FitchVars(offset_UStaticMeshComponent_StaticMesh, netvars);
			FitchVars(offset_UWeaponMeshComponent_AttachedStaticComponentMap, netvars);
			FitchVars(offset_UWeaponMeshComponent_ReplicatedSkinParam, netvars);
			FitchVars(offset_UCharacterMovementComponent_Velocity, netvars);
			FitchVars(offset_UCharacterMovementComponent_JumpZVelocity, netvars);
			FitchVars(offset_UCharacterMovementComponent_WalkableFloorZ, netvars);
			FitchVars(offset_UCharacterMovementComponent_LastUpdateLocation, netvars);
			FitchVars(offset_UCharacterMovementComponent_LastUpdateRotation, netvars);
			FitchVars(offset_UCharacterMovementComponent_LastUpdateVelocity, netvars);
			FitchVars(offset_UCharacterMovementComponent_CurrentFloor, netvars);
			FitchVars(offset_UCharacterMovementComponent_bit4, netvars);
			FitchVars(offset_ACharacter_CharacterMovement, netvars);
			FitchVars(offset_ACharacter_Mesh, netvars);
			FitchVars(offset_UVehicleRiderComponent_SeatIndex, netvars);
			FitchVars(offset_UVehicleRiderComponent_LastVehiclePawn, netvars);
			FitchVars(offset_UWeaponProcessorComponent_EquippedWeapons, netvars);
			FitchVars(offset_UWeaponProcessorComponent_WeaponIndex, netvars);
			FitchVars(offset_ATslCharacterBase_Health, netvars);
			FitchVars(offset_HealthFlag1, netvars);
			FitchVars(offset_HealthFlag2, netvars);
			FitchVars(offset_HealthFlag3, netvars);
			FitchVars(offset_HealthIndex1, netvars);
			FitchVars(offset_HealthIndex2, netvars);
			FitchVars(offset_HealthXorKeys, netvars);
			FitchVars(offset_HealthDecryptFunction, netvars);
			FitchVars(offset_ATslCharacterBase_HealthMax, netvars);
			FitchVars(offset_ATslCharacterBase_WeaponProcessor, netvars);
			FitchVars(offset_ATslCharacter_Team, netvars);
			FitchVars(offset_ATslCharacter_InventoryFacade, netvars);
			FitchVars(offset_ATslCharacter_VehicleRiderComponent, netvars);
			FitchVars(offset_ATslCharacter_GroggyHealth, netvars);
			FitchVars(offset_ATslCharacter_GroggyHealthMax, netvars);
			FitchVars(offset_ATslCharacter_AimOffsets, netvars);
			FitchVars(offset_ATslCharacter_LastAimOffsets, netvars);
			FitchVars(offset_ATslCharacter_ScopingCamera, netvars);
			FitchVars(offset_ATslCharacter_SpectatedCount, netvars);
			FitchVars(offset_ATslCharacter_LastTeamNum, netvars);
			FitchVars(offset_ATslCharacter_CharacterName, netvars);
			FitchVars(offset_APlayerController_AcknowledgedPawn, netvars);
			FitchVars(offset_APlayerController_PlayerCameraManager, netvars);
			FitchVars(offset_APlayerController_MyHUD, netvars);
			FitchVars(offset_APlayerController_MapSig, netvars);
			FitchVars(offset_APlayerController_RotationInput, netvars);
			FitchVars(offset_APlayerController_InputYawScale, netvars);
			FitchVars(offset_APlayerController_InputPitchScale, netvars);
			FitchVars(offset_APlayerController_InputRollScale, netvars);
			FitchVars(offset_ATslPlayerController_MaxValidPing, netvars);
			FitchVars(offset_ATslPlayerController_PlayerInput, netvars);
			FitchVars(offset_APlayerState_PlayerName, netvars);
			FitchVars(offset_APlayerState_Ping, netvars);
			FitchVars(offset_ATslPlayerState_PlayerStatistics, netvars);
			FitchVars(offset_ATslPlayerState_PubgIdData, netvars);
			FitchVars(offset_ATslPlayerState_DamageDealtOnEnemy, netvars);
			FitchVars(offset_ATslPlayerState_PartnerLevel, netvars);
			FitchVars(offset_AWheeledVehicle_Mesh, netvars);
			FitchVars(offset_AWheeledVehicle_VehicleMovement, netvars);
			FitchVars(offset_ATslFloatingVehicle_Mesh, netvars);
			FitchVars(offset_ATslFloatingVehicle_VehicleCommonComponent, netvars);
			FitchVars(offset_ATslWheeledVehicle_VehicleCommonComponent, netvars);
			FitchVars(offset_ADroppedItem_Item, netvars);
			FitchVars(offset_UItem_StackCount, netvars);
			FitchVars(offset_UItem_ItemTableRowPtr, netvars);
			FitchVars(offset_ItemTableRowBase_ItemName, netvars);
			FitchVars(offset_ItemTableRowBase_ItemCategory, netvars);
			FitchVars(offset_ItemTableRowBase_ItemDetailedName, netvars);
			FitchVars(offset_ItemTableRowBase_ItemDescription, netvars);
			FitchVars(offset_ItemTableRowBase_ItemID, netvars);
			FitchVars(offset_UDroppedItemInteractionComponent_Item, netvars);
			FitchVars(offset_AInventory_Items, netvars);
			FitchVars(offset_UEquipableItem_EquipSlotID, netvars);
			FitchVars(offset_UEquipableItem_DurabilityMax, netvars);
			FitchVars(offset_UEquipableItem_Durability, netvars);
			FitchVars(offset_UEquipableItem_ReplicatedSkinItem, netvars);
			FitchVars(offset_AEquipment_Items, netvars);
			FitchVars(offset_AItemPackage_Items, netvars);
			FitchVars(offset_ATslWeapon_Mesh3P, netvars);
			FitchVars(offset_ATslWeapon_MuzzleAttachPoint, netvars);
			FitchVars(offset_ATslWeapon_FiringAttachPoint, netvars);
			FitchVars(offset_ATslWeapon_AttachedItem, netvars);
			FitchVars(offset_ATslWeapon_Gun_ScopingAttachPoint, netvars);
			FitchVars(offset_ATslWeapon_Gun_ScopingFocusPoint, netvars);
			FitchVars(offset_ATslWeapon_Gun_CurrentAmmoData, netvars);
			FitchVars(offset_ATslWeapon_Gun_CurrentZeroLevel, netvars);
			FitchVars(offset_ATslWeapon_Trajectory_TrajectoryGravityZ, netvars);
			FitchVars(offset_ATslWeapon_Trajectory_WeaponTrajectoryData, netvars);
			FitchVars(offset_WeaponTrajectoryData_TrajectoryConfig, netvars);
			FitchVars(offset_ATslProjectile_ProjectileConfig, netvars);
			FitchVars(offset_ATslProjectile_CollisionComp, netvars);
			FitchVars(offset_ATslProjectile_ExplosionDelay, netvars);
			FitchVars(offset_ATslProjectile_TimeTillExplosion, netvars);
			FitchVars(offset_UTslSettings_BallisticDragScale, netvars);
			FitchVars(offset_UTslSettings_BallisticDropScale, netvars);
			FitchVars(offset_UBodySetup_WalkableSlopeOverride, netvars);
			FitchVars(offset_UWidget_Visibility, netvars);
			FitchVars(offset_UWidget_Slot, netvars);
			FitchVars(offset_UCanvasPanelSlot_LayoutData, netvars);
			FitchVars(offset_UTslNewWorldMapWidget_MapGrid, netvars);
			FitchVars(offset_TslTrainingWorldMapWidget_TrainingMapGrid, netvars);
			FitchVars(offset_UMinimapCanvasWidget_SelectMinimapSizeIndex, netvars);
			FitchVars(offset_UMinimapCanvasWidget_MinimapSizeOffset, netvars);
			FitchVars(offset_UTslGameUserSettings_SelectMiniMapIndex, netvars);
			FitchVars(offset_AInventoryFacade_Inventory, netvars);
			FitchVars(offset_AInventoryFacade_Equipment, netvars);


		}

		void FixOffset()
		{
			if (g_PatternData.UObjectArray < g_PatternData.ModuleHandle)
			{
				g_PatternData.ptr_GetMousePostion += g_PatternData.ModuleHandle;
				g_PatternData.offset_PxScene += g_PatternData.ModuleHandle;
				g_PatternData.GameTimePtr += g_PatternData.ModuleHandle;
				g_PatternData.retaddrofLineTrace += g_PatternData.ModuleHandle;
				g_PatternData.offset_HealthDecryptFunction += g_PatternData.ModuleHandle;
				g_PatternData.offset_JmpR14 += g_PatternData.ModuleHandle;
				g_PatternData.offset_JmpR15 += g_PatternData.ModuleHandle;
				g_PatternData.fnProcessEvent += g_PatternData.ModuleHandle;
				g_PatternData.fnGetNames += g_PatternData.ModuleHandle;
				g_PatternData.GNames += g_PatternData.ModuleHandle;
				g_PatternData.UObjectArray += g_PatternData.ModuleHandle;
				g_PatternData.UObjectArrayNum += g_PatternData.ModuleHandle;
				g_PatternData.UWrold_Ptr += g_PatternData.ModuleHandle;
				g_PatternData.UWorld += g_PatternData.ModuleHandle;
				g_PatternData.decryptUWorld += g_PatternData.ModuleHandle;
				g_PatternData.decryptOwningGameInstance += g_PatternData.ModuleHandle;
				g_PatternData.decryptLocalPlayers += g_PatternData.ModuleHandle;
				g_PatternData.decryptViewportClient += g_PatternData.ModuleHandle;
				g_PatternData.decryptPlayerController += g_PatternData.ModuleHandle;
				g_PatternData.decryptPersistentLevel += g_PatternData.ModuleHandle;
				g_PatternData.encryAActors += g_PatternData.ModuleHandle;
				g_PatternData.decryptAActors += g_PatternData.ModuleHandle;
				g_PatternData.decryptUObject += g_PatternData.ModuleHandle;
				g_PatternData.decryptUObjectIndex += g_PatternData.ModuleHandle;
				g_PatternData.decryptUObjectArray += g_PatternData.ModuleHandle;
				g_PatternData.fnGetOffset += g_PatternData.ModuleHandle;
				g_PatternData.fnFindTextInLocalizationTable += g_PatternData.ModuleHandle;
				g_PatternData.ExtFindTextInLocalizationTableRcx += g_PatternData.ModuleHandle;
				g_PatternData.ExtFindTextInLocalizationTableCall += g_PatternData.ModuleHandle;
				g_PatternData.fnLineTraceSingle += g_PatternData.ModuleHandle;
				g_PatternData.fnLineTraceSingleByChannel += g_PatternData.ModuleHandle;
				g_PatternData.pDefaultQueryParam += g_PatternData.ModuleHandle;
				g_PatternData.pDefaultResponseParam += g_PatternData.ModuleHandle;
				g_PatternData.fnFCollisionQueryParamsConstructible += g_PatternData.ModuleHandle;
				g_PatternData.fnFCollisionQueryParamsDestructor += g_PatternData.ModuleHandle;
				g_PatternData.fnGetTslSettingsInstance += g_PatternData.ModuleHandle;
				g_PatternData.fnGetPhysXScene += g_PatternData.ModuleHandle;
				g_PatternData.fnraycastIndex += g_PatternData.ModuleHandle;
				g_PatternData.fnSetHitResultFromShapeAndFaceIndex += g_PatternData.ModuleHandle;
				g_PatternData.offset_Language += g_PatternData.ModuleHandle;
				g_PatternData.offset_BackPackState += g_PatternData.ModuleHandle;
			}
		}

		void ReFixOffset()
		{
			if (g_PatternData.UObjectArray > g_PatternData.ModuleHandle)
			{
				g_PatternData.ptr_GetMousePostion -= g_PatternData.ModuleHandle;
				g_PatternData.offset_PxScene -= g_PatternData.ModuleHandle;
				g_PatternData.GameTimePtr -= g_PatternData.ModuleHandle;
				g_PatternData.retaddrofLineTrace -= g_PatternData.ModuleHandle;
				g_PatternData.offset_HealthDecryptFunction -= g_PatternData.ModuleHandle;
				g_PatternData.offset_JmpR14 -= g_PatternData.ModuleHandle;
				g_PatternData.offset_JmpR15 -= g_PatternData.ModuleHandle;
				g_PatternData.fnProcessEvent -= g_PatternData.ModuleHandle;
				g_PatternData.fnGetNames -= g_PatternData.ModuleHandle;
				g_PatternData.GNames -= g_PatternData.ModuleHandle;
				g_PatternData.UObjectArray -= g_PatternData.ModuleHandle;
				g_PatternData.UObjectArrayNum -= g_PatternData.ModuleHandle;
				g_PatternData.UWrold_Ptr -= g_PatternData.ModuleHandle;
				g_PatternData.UWorld -= g_PatternData.ModuleHandle;
				g_PatternData.decryptUWorld -= g_PatternData.ModuleHandle;
				g_PatternData.decryptOwningGameInstance -= g_PatternData.ModuleHandle;
				g_PatternData.decryptLocalPlayers -= g_PatternData.ModuleHandle;
				g_PatternData.decryptViewportClient -= g_PatternData.ModuleHandle;
				g_PatternData.decryptPlayerController -= g_PatternData.ModuleHandle;
				g_PatternData.decryptPersistentLevel -= g_PatternData.ModuleHandle;
				g_PatternData.encryAActors -= g_PatternData.ModuleHandle;
				g_PatternData.decryptAActors -= g_PatternData.ModuleHandle;
				g_PatternData.decryptUObject -= g_PatternData.ModuleHandle;
				g_PatternData.decryptUObjectIndex -= g_PatternData.ModuleHandle;
				g_PatternData.decryptUObjectArray -= g_PatternData.ModuleHandle;
				g_PatternData.fnGetOffset -= g_PatternData.ModuleHandle;
				g_PatternData.fnFindTextInLocalizationTable -= g_PatternData.ModuleHandle;
				g_PatternData.ExtFindTextInLocalizationTableRcx -= g_PatternData.ModuleHandle;
				g_PatternData.ExtFindTextInLocalizationTableCall -= g_PatternData.ModuleHandle;
				g_PatternData.fnLineTraceSingle -= g_PatternData.ModuleHandle;
				g_PatternData.fnLineTraceSingleByChannel -= g_PatternData.ModuleHandle;
				g_PatternData.pDefaultQueryParam -= g_PatternData.ModuleHandle;
				g_PatternData.pDefaultResponseParam -= g_PatternData.ModuleHandle;
				g_PatternData.fnFCollisionQueryParamsConstructible -= g_PatternData.ModuleHandle;
				g_PatternData.fnFCollisionQueryParamsDestructor -= g_PatternData.ModuleHandle;
				g_PatternData.fnGetTslSettingsInstance -= g_PatternData.ModuleHandle;
				g_PatternData.fnGetPhysXScene -= g_PatternData.ModuleHandle;
				g_PatternData.fnraycastIndex -= g_PatternData.ModuleHandle;
				g_PatternData.fnSetHitResultFromShapeAndFaceIndex -= g_PatternData.ModuleHandle;
				g_PatternData.offset_Language -= g_PatternData.ModuleHandle;
				g_PatternData.offset_BackPackState -= g_PatternData.ModuleHandle;
			}
		}
	}
}